### ISSUE TITLE
无法使用，因为姿势不对

### ISSUE THREAD

**Issue by wangbs95** [beyondfengyu/HappyChat#5]
项目启动后访问localhost:9688或者ws://localhost:8099/websocket都无法访问

**Comment by wangbs95** [comment]
可以使用，正确打开姿势为：
1、启动server
2、修改docs/bootstrap/js/chat.js中websocket.url为本机地址（如ws://192.168.30.43:9688/websocket），然后修改index.html中对chat.js的引用路径为本地相对路径，打开HTML。
3、若需演示，可将docs文件夹打包给同事，在局域网内可访问。

**Comment by SuperHanKunLin** [comment]
还是不太会啊，能更详细一点吗

**Comment by wangbs95** [comment]
> 还是不太会啊，能更详细一点吗

太久远了，不记得了
